# Generated by Django 3.2.6 on 2023-12-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nitk_hack', '0002_alter_project_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_file',
            field=models.FileField(upload_to='myprojects/Nitk_hack/uploads'),
        ),
    ]
